// packages/solid/src/styledRuntime.tsx
import { ParentComponent, splitProps, ValidComponent, JSX } from 'solid-js';
import { Dynamic } from 'solid-js/web';

export function styledRuntime(el: ValidComponent, className: string) {
  let Component: ParentComponent<{
    class?: string;
    style?: JSX.CSSProperties;
  }> = (props) => {
    let [local, others] = splitProps(props, ['class']);

    return (
      <Dynamic
        component={el}
        class={[local.class, className].filter(Boolean).join(' ')}
        {...others}
      />
    );
  };
  return Component;
}

// packages/react/src/styledRuntime.ts
import { createElement } from 'react';

export function styledRuntime<T extends keyof JSX.IntrinsicElements>(
  el: T,
  className: string,
) {
  const Component = function Component(props: React.ComponentProps<T>) {
    return createElement(el, {
      ...props,
      className: [props.className, className].filter(Boolean).join(' '),
    });
  };

  Component.displayName = `DBStyled(${el})`;

  return Component;
}
